[workspace]
members = [
    "apps/threshold/src-tauri",
    "plugins/alarm-manager",
    "plugins/app-management",
    "plugins/predictive-back",
    "plugins/wear-sync",
    "plugins/theme-utils",
    "plugins/os-prefs",
    "plugins/toast",
]
exclude = ["vendor/tauri-plugins-workspace"]
resolver = "2"

[profile.release]
strip = false
