// Alarm data models shared with TypeScript, plus their generated bindings
//
// (c) Copyright 2026 Liminal HQ, Scott Morris
// SPDX-License-Identifier: Apache-2.0 OR MIT

use serde::{Deserialize, Serialize};

/// Complete alarm configuration (returned to TypeScript)
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
pub struct AlarmRecord {
    pub id: i32,
    pub label: Option<String>,
    pub enabled: bool,
    #[cfg_attr(test, ts(type = "AlarmMode"))]
    pub mode: AlarmMode,
    pub fixed_time: Option<String>,   // "HH:MM"
    pub window_start: Option<String>, // "HH:MM"
    pub window_end: Option<String>,   // "HH:MM"
    pub active_days: Vec<i32>,        // [0-6] where 0=Sun
    // i64 -> bigint by default in ts-rs; these are millisecond timestamps and
    // a revision counter, both safely within JS's Number.MAX_SAFE_INTEGER for
    // the app's realistic lifetime, and all existing call sites already treat
    // them as `number`.
    #[cfg_attr(test, ts(type = "number | null"))]
    pub next_trigger: Option<i64>, // Epoch millis
    pub sound_uri: Option<String>,
    pub sound_title: Option<String>,
    #[cfg_attr(test, ts(type = "number"))]
    pub revision: i64,
}

/// Input for creating/updating alarms (from TypeScript)
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
pub struct AlarmInput {
    #[cfg_attr(test, ts(optional = nullable))]
    pub id: Option<i32>,
    #[cfg_attr(test, ts(optional = nullable))]
    pub label: Option<String>,
    pub enabled: bool,
    #[cfg_attr(test, ts(type = "AlarmMode"))]
    pub mode: AlarmMode,
    #[cfg_attr(test, ts(optional = nullable))]
    pub fixed_time: Option<String>,
    #[cfg_attr(test, ts(optional = nullable))]
    pub window_start: Option<String>,
    #[cfg_attr(test, ts(optional = nullable))]
    pub window_end: Option<String>,
    pub active_days: Vec<i32>,
    #[cfg_attr(test, ts(optional = nullable))]
    pub sound_uri: Option<String>,
    #[cfg_attr(test, ts(optional = nullable))]
    pub sound_title: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum AlarmMode {
    Fixed,
    Window,
}

impl Default for AlarmInput {
    fn default() -> Self {
        Self {
            id: None,
            label: None,
            enabled: true,
            mode: AlarmMode::Fixed,
            fixed_time: Some("07:00".into()),
            window_start: None,
            window_end: None,
            active_days: vec![1, 2, 3, 4, 5], // Weekdays
            sound_uri: None,
            sound_title: None,
        }
    }
}

/// Generates `apps/threshold/src/types/alarm.ts` from the types above and
/// keeps it honest: this test fails if the committed file has drifted from
/// a fresh generation, so `AlarmRecord`/`AlarmInput` can't silently diverge
/// from `types/alarm.ts` the way the hand-maintained version did (it was
/// missing `revision` entirely).
///
/// To regenerate after changing a `#[cfg_attr(test, ...)]`-annotated type
/// here, run:
///   UPDATE_TS_BINDINGS=1 cargo test -p threshold ts_bindings -- --nocapture
#[cfg(test)]
mod ts_bindings {
    use super::*;
    use std::fs;
    use std::path::PathBuf;
    use ts_rs::TS;

    const HEADER: &str = "\
// GENERATED FILE -- DO NOT EDIT BY HAND.
// Source: apps/threshold/src-tauri/src/alarm/models.rs
// Regenerate with: UPDATE_TS_BINDINGS=1 cargo test -p threshold ts_bindings -- --nocapture

import { AlarmMode } from '@threshold/core/types';
export { AlarmMode };
";

    /// ts-rs prefixes every export with its own "generated by ts-rs" banner
    /// comment; strip it since the combined file has one shared header.
    fn strip_ts_rs_banner(generated: &str) -> String {
        generated
            .lines()
            .skip_while(|line| line.starts_with("//") || line.trim().is_empty())
            .collect::<Vec<_>>()
            .join("\n")
    }

    fn generate() -> String {
        let cfg = ts_rs::Config::new();
        let record = strip_ts_rs_banner(&AlarmRecord::export_to_string(&cfg).unwrap());
        let input = strip_ts_rs_banner(&AlarmInput::export_to_string(&cfg).unwrap());
        format!("{HEADER}\n{record}\n\n{input}\n")
    }

    fn output_path() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../src/types/alarm.ts")
    }

    #[test]
    fn alarm_ts_bindings_are_up_to_date() {
        let generated = generate();
        let path = output_path();

        if std::env::var("UPDATE_TS_BINDINGS").is_ok() {
            fs::write(&path, &generated)
                .expect("failed to write apps/threshold/src/types/alarm.ts");
            return;
        }

        let committed = fs::read_to_string(&path).unwrap_or_default();
        assert_eq!(
            committed, generated,
            "\n\napps/threshold/src/types/alarm.ts is out of sync with alarm/models.rs.\n\
             Regenerate with: UPDATE_TS_BINDINGS=1 cargo test -p threshold ts_bindings -- --nocapture\n"
        );
    }

    /// `AlarmMode` is deliberately hand-maintained TS-side (see the module
    /// doc comment above), so it isn't covered by the drift check above --
    /// nothing stops its Rust variants and TS enum members from silently
    /// diverging. This test can't inspect `packages/core/src/types.ts`
    /// directly, but hardcoding the wire values here means renaming a
    /// variant is a compile error in this test, forcing whoever does it to
    /// come here and update `AlarmMode` in `packages/core/src/types.ts` too.
    #[test]
    fn alarm_mode_wire_values_match_hand_maintained_ts_enum() {
        assert_eq!(
            serde_json::to_value(AlarmMode::Fixed).unwrap(),
            serde_json::json!("FIXED"),
            "packages/core/src/types.ts: AlarmMode.Fixed must serialise to 'FIXED'"
        );
        assert_eq!(
            serde_json::to_value(AlarmMode::Window).unwrap(),
            serde_json::json!("WINDOW"),
            "packages/core/src/types.ts: AlarmMode.Window must serialise to 'WINDOW'"
        );
    }
}
