#!/usr/bin/env bash
# Check every source file has the licence header AGENTS.md requires
#
# (c) Copyright 2026 Liminal HQ, Scott Morris
# SPDX-License-Identifier: Apache-2.0 OR MIT

# Exits 1 and lists offenders if any file is missing an
# SPDX-License-Identifier line within its first few lines; 0 if clean.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

# Files that are exempt: generated output the build regenerates from
# scratch (adding a header would just create drift against the
# generator), and tool-scaffolded boilerplate nobody hand-writes.
EXEMPT_FILES=(
  "apps/threshold/src/types/alarm.ts"       # generated by alarm::models::ts_bindings
  "apps/threshold/vite.config.ts"           # build-tool config
  "apps/threshold/src/vite-env.d.ts"        # Vite-scaffolded ambient types
  "tools/release-tui/vitest.config.ts"      # build-tool config
  "plugins/*/rollup.config.js"              # build-tool config
  "plugins/toast/android/src/test/java/ExampleUnitTest.kt"            # Android Studio scaffold
  "plugins/toast/android/src/androidTest/java/ExampleInstrumentedTest.kt" # Android Studio scaffold
)

is_exempt() {
  local f="$1"
  for exempt in "${EXEMPT_FILES[@]}"; do
    # shellcheck disable=SC2053  # intentional glob match, not literal compare
    [[ "$f" == $exempt ]] && return 0
  done
  return 1
}

missing=()

while IFS= read -r -d '' f; do
  is_exempt "$f" && continue
  if ! head -8 "$f" | grep -q "SPDX-License-Identifier"; then
    missing+=("$f")
  fi
done < <(find apps packages plugins scripts tools \
  \( -name node_modules -o -name dist -o -name dist-js -o -name build \
     -o -name target -o -name gen -o -name .tauri \) -prune -o \
  \( -name "*.rs" -o -name "*.kt" -o -name "*.ts" -o -name "*.tsx" \
     -o -name "*.js" -o -name "*.mjs" -o -name "*.sh" \) -print0)

if [ "${#missing[@]}" -gt 0 ]; then
  echo "Missing licence header (see AGENTS.md 'Licence and Copyright'):"
  for f in "${missing[@]}"; do
    echo "  $f"
  done
  echo
  echo "${#missing[@]} file(s) missing a header."
  exit 1
fi

echo "All source files have licence headers."
